---

- name: Enable IP forwarding
  command: sysctl net.ipv4.ip_forward=1

- name: Enable /proc/sys/net/bridge/bridge-nf-call-iptables
  command: sysctl net.bridge.bridge-nf-call-iptables=1

- name: Setup WeaveNet
  become: false
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  args:
    executable: /bin/bash
