all:
  children:

    kubernetes:
      children:

        kubernetes-masters:
          hosts:
            kube-master-01:
              ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_location }}"

        # kubernetes-workers:
        #   hosts:
            # Add worker hosts here
