---

- name: Add user-roles directory for user - {{ item }}
  file:
    path: "{{ user_roles_dir }}/{{ item }}"
    state: directory


- name: Copy role-manifests for user - {{ item }}
  template:
    src: "{{ ansible_templates_dir }}/user-rbac.yml.j2"
    dest: "{{ user_roles_dir }}/{{ item }}/user-rbac.yml"
  vars:
    user: "{{ item }}"

- name: Apply roles for user - {{ item }}
  become: false
  command: kubectl apply -f "{{ user_roles_dir }}/{{ item }}/user-rbac.yml"
